In [3]:
import numpy as np
from numpy import linalg as LA
m = np.asmatrix([[2.5,0.5,2.2,1.9,3.1,2.3,2.0,1.0,1.5,1.1],[2.4,0.7,2.9,2.2,3.0,2.7,1.6,1.1,1.6,0.9]])
w, v = LA.eig(np.diag((1, 2, 3)))
w, v

(array([ 1.,  2.,  3.]), array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]]))

In [2]:
w

array([ 1.,  2.,  3.])

In [10]:
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
a = np.diag((1, 2, 3))
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
type(m)
a,b = LA.eig(m)

In [16]:
a

array([1.26032778, 0.03967222])

In [20]:
bInv = b.I

In [21]:
b

matrix([[ 0.88697868,  0.46181038],
        [-0.46181038,  0.88697868]])

In [22]:
bInv

matrix([[ 0.88697868, -0.46181038],
        [ 0.46181038,  0.88697868]])

In [23]:
bInv*b

matrix([[ 1.00000000e+00, -5.55111512e-17],
        [ 0.00000000e+00,  1.00000000e+00]])

In [24]:
aMat = np.diag(a)

In [25]:
aMat

array([[1.26032778, 0.        ],
       [0.        , 0.03967222]])

In [26]:
b*aMat*bInv

matrix([[ 1. , -0.5],
        [-0.5,  0.3]])

# Exemplo da Chinesa

In [67]:
n=10
m1 = m[0]
m1M = round(m1.mean(),3)
m2 = m[1]
m2M = round(m2.mean(),3)
m1M,m2M

(1.81, 1.91)

In [68]:
mBarra = np.asmatrix([[1.81,1.81,1.81,1.81,1.81,1.81,1.81,1.81,1.81,1.81],[1.91,1.91,1.91,1.91,1.91,1.91,1.91,1.91,1.91,1.91]])
mBarra

matrix([[ 1.81,  1.81,  1.81,  1.81,  1.81,  1.81,  1.81,  1.81,  1.81,
          1.81],
        [ 1.91,  1.91,  1.91,  1.91,  1.91,  1.91,  1.91,  1.91,  1.91,
          1.91]])

In [69]:
mSM = m-mBarra
Covarrm = (mSM*mSM.transpose())/(n-1)
Covarrm

matrix([[ 0.61655556,  0.61544444],
        [ 0.61544444,  0.71655556]])

# Calculo da Matrix de Covariância - Exemplo

Utilizaremos a Matriz **X$_{3x5}$** conforme descrita a seguir:

In [49]:
X = np.asmatrix([[4.0,2.0,0.6],[4.2,2.1,0.59],[3.9,2.0,0.58],[4.3,2.1,0.62],[4.1,2.2,0.63]])
n = 5 # números de amostras

Como se pode observar a Matrix *X* possui 5 linhas e 3 colunas onde cada linha representa uma amostra e cada coluna uma variável. Para o cálculo da matrix de Covariância  de **X** (**C$_{X}$**) temos que subutrair a média de cada variável de sua respectiva coluna, ou seja, temos que calcular $x-\bar{x}$ para cada valor da coluna 1, 2, 3.

In [50]:
x1 = X[:,0]# acesso a coluna 1
x2 = X[:,1]#acesso a coluna 2
x3 = X[:,2]#acesso a coluna 3
x1M = float("{0:.2f}".format(x1.mean())) #média de x1
x2M = round(x2.mean(), 2) #média de x2
x3M = float("{0:.3f}".format(x3.mean())) #média de x3

Para subtrairmos a média da matriz $X$ contruimos uma matriz com a médias no seguinte formato:<br>
<center>$\begin{bmatrix} 4.1 & 2.08 & 0.604 \\ 4.1 & 2.08 & 0.604 \\ 4.1 & 2.08 & 0.604 \\ 4.1 & 2.08 & 0.604 \\ 4.1 & 2.08 & 0.604 \end{bmatrix}$<br>

Assim podemos subtrair Matriz média $\bar{X}$ da Matrix **$X$** gerando assim a Matriz **$X_{m}$** já com a média subtraída 

In [51]:
#Gerando a Matrix Média
Xbarra = np.asmatrix([[4.10,2.08,0.604],[4.10,2.08,0.604],[4.10,2.08,0.604],[4.10,2.08,0.604],[4.10,2.08,0.604]])
#Subtraindo a matriz média(Xbarra) da matrix original (X)
Xm = X-Xbarra

Despois de Calculada a Matriz já subtraída a média, para encontrar a matriz de Covariância devemos calcular $\frac{X_{m}*X_{m}^{T}}{n-1}$ isso se a sua matriz tiver as váriáves como linhas e amostras como colunas. No nosso caso a nossa matriz tem as variáveis como coluna e amostras como linhas, então a fórmula muda para $\frac{X_{m}^{T}*X_{m}}{n-1}$, logo a matrix de $Covarr_{X}$ é :


In [52]:
CovarrX = (Xm.transpose()*Xm)/(n-1) # Cálculo da Matriz de Covariância de X

matrix([[ 0.025  ,  0.0075 ,  0.00175],
        [ 0.0075 ,  0.007  ,  0.00135],
        [ 0.00175,  0.00135,  0.00043]])